djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path,include
from hellosite import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/',views.search),
    path('',include('hellosite.urls')),
]

djangoProject/hellosite/urls.py
from django.urls import path,re_path
from hellosite import views
from hellosite.views import *
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.generic.base import TemplateView
from django.http import HttpResponse
app_name="hellosite"
urlpatterns = [
    path('', views.search, name='search'),
    path('search',views.search,name='search'),
    re_path(r'^display',views.display,name='display'),
    # path('graph',views.graph,name='display'),
    path(r'graph/<str:sid>', views.graph,name="graph"),
    url('sub',views.sub,name='sub')
]

djangoProject/hellosite/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username=models.CharField('用户名',max_length=30)
    userpass=models.CharField('密码',max_length=30)
    useremail=models.EmailField('邮箱',max_length=30)
    usertype=models.CharField('用户类型',max_length=30)

    def __str__(self):
        return self.username

djangoProject/hellosite/views.py
from django.shortcuts import render
from django.http import HttpResponse
import json
from .models import User
import requests


# Create your views here.
def search(request):
    return render(request, 'begin/search.html')


def display(request):
    m = request.GET['wd']
    # m=m.split(" ")
    type = request.GET['type']
    start = request.GET['start']
    type = int(type)
    # print(type)
    post = {}
    post["type"] = "RetrievalPapers"
    post["query"] = m
    if type:
        post["sortByValue"] = 1
    else:
        post["sortByValue"] = 0
    post["start"] = start
    if int(start) < 10:
        post["previous"] = 0
    else:
        post["previous"] = int(start) - 10
    post["next"] = int(start) + 10
    r = requests.get(url='http://182.92.1.145:8050/query', params=post)
    data = json.loads(r.text)
    print(data)
    return render(request, 'begin/display.html',
                  {'next': data["next"], "previous": data["previous"], 'type': '0', 'start': data["start"],
                   'total': data["hits"]['total'],
                   'hits': data['hits']['hit'][int(data["start"]):int(data["start"]) + 10], 'query': data['query']})


def graph(request, sid):
    post = {}
    post["type"] = "RetrievalNetwork"
    post["query"] = sid
    r = requests.get(url='http://182.92.1.145:8050/networks', params=post)
    data = json.loads(r.text)
    print(type(data))
    print(data)
    res = {}
    subgraph = data["subgraph"]
    nodes = subgraph["nodes"]
    res["subgraph"] = subgraph
    for node in nodes:
        res[str(node["id"])] = node
    f = open(
        '/Users/melon/Desktop/Postgraduate/Course/IR/HW/project3-group7/djangoProject/hellosite/templates/begin/sub3.json',
        'w')
    json.dump(res, f)
    f.close()
    return render(request, 'begin/graph.html')


def sub(request):
    f = open(
        '/Users/melon/Desktop/Postgraduate/Course/IR/HW/project3-group7/djangoProject/hellosite/templates/begin/sub3.json',
        'r')
    content = f.read()
    a = json.loads(content)
    print(a["subgraph"].keys())
    return HttpResponse(json.dumps(a), content_type="application/json")

djangoProject/hellosite/templates/begin/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
     <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/css/main.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
    body{
	{#width:150px;#}
	{#height: 80px;#}
	background-image:url("../../static/images/back.jpg");
	background-attachment:fixed;
	background-repeat: no-repeat;
}
    .spacer {
    padding-top: 90px;
    padding-bottom: 40px
}
.spacer_s {
    padding-top: 30px;
    padding-bottom: 10px
}
.form-horizontal{
    display:block;
    width:50%;
    margin:0 auto;
}
.p1 {
  font-family: "Times New Roman", Times, serif;
}
    </style>
</head>
<body style="">

{#define navigation bar#}
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
	<div class="navbar-header">
		<a class="navbar-brand" href="search" class="p1" style="font-family: 'PingFang SC'">Paper Network</a>
	</div>
	<div>
		<ul class="nav navbar-nav">
{#			<li ><a href="demo" class="p1">Graph Demo</a></li>#}
{#			<li><a href="{% url 'hellosite:search' %}" class="p1">Search</a></li>#}
		</ul>
	</div>
	</div>
</nav>
{% block content %}

{% endblock content %}
    </body>
</html>

djangoProject/hellosite/templates/begin/display.html
{#{% extends "begin/base.html" %}#}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Serach Result</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/css/main.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        body{
	{#width:150px;#}
	{#height: 80px;#}
	background-image:url("../../static/images/back.jpg");
	{#background-attachment:fixed;#}
	background-repeat: no-repeat;
}
        .spacer {
            padding-top: 90px;
            padding-bottom: 40px
        }

        .spacer_s {
            padding-top: 30px;
            padding-bottom: 10px
        }

        .form-horizontal {
            display: block;
            width: 50%;
            margin: 0 auto;
        }
        .paper_title{
            font-family: "PingFang SC";
            font-size: 19px;
        }
        .paper_ref{
            font-family:"Times New Roman";
            font-size: 19px;
        }
        .grpah_button{
            font-family: "Helvetica Neue";
            font-size: 17px;
        }
        .p1 {
            font-family: "Times New Roman", Times, serif;
        }
    </style>
</head>

{#<script>#}
{#    function  showvalf(){#}
{#        var getval=localStorage.getItem("result");#}
{#        var a=getval.split(" ");#}
{#        var result="";#}
{#        for(let i=0;i<a.length;++i)#}
{#        {#}
{#            var p=a[i];#}
{#            console.log(p);#}
{#            result+='<li class=\"list-group-item text-center> <a href="graph{{ p }}">'+a[i]+'</a></li>';#}
{#        }#}
{#        console.log(result);#}
{##}
{#        document.getElementById("result").innerHTML=result;#}
{##}
{#  }#}
{#</script>#}
<body>
{#onload="showvalf()"#}
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="search" class="p1" style="font-family: 'PingFang SC'">Paper Network</a>
        </div>
        <div>
            <ul class="nav navbar-nav">
{#                <li><a href="{% url 'hellosite:hello' %}" class="p1">Home</a></li>#}
{#                <li><a href="{% url 'hellosite:search' %}" class="p1">Search</a></li>#}
            </ul>
        </div>
    </div>
</nav>
{#{% block content %}#}
<header class="text-center text-white masthead">
    <div class="container">
{#        <div class="spacer_s"></div>#}
        <div class="row">
            <div>
                <h2 class="p1"> Choose a paper to build a graph:</h2>
            </div>
            <div class="spacer_s"></div>
            <div id="result" class="p1">
                {#            <li class=\"list-group-item text-center>#}
                {#                {{ query }}#}
                {#            </li>#}
                {% for hit in hits %}
                    <div class="card bg-info text-center " style="border-radius:10px;width: 80rem; margin: 0 auto;">
                    <a href="/graph/{{ hit.Sid }}">
                        <br>
{#                        <br>#}
                        <div class="card-header paper_title">

                            {{ hit.title }}

                        </div>
                        <div class="card-body">
{#                            <h5 class="card-title p1">Special title treatment</h5>#}
                            <p class="card-text paper_ref">{{ hit.outCitationsCount }} Citations , {{ hit.inCitationsCount }} References</p>
{#                            <a href="/graph/{{ hit.title }}" class="btn btn-primary grpah_button">Build A Graph!</a>#}
{#                            <br>#}
{#                            <br>#}

                        </div>
                    </a>
{#                        <div class="card-footer text-muted">#}
{#                            2 days ago#}
{#                        </div>#}
                    </div>
                    <br>
{#                            <br>#}
                {% endfor %}

                {#            {% for m in message %}#}
                {#                <li class=\"list-group-item text-center>#}
                {#                    <a href="/graph/{{ m }}">{{ m }}</a>#}
                {#                </li>#}
                {#            {% endfor %}#}
            </div>
        <ul class="pager">

            <li class="previous"><a href="display?wd={{ query }}&start={{ previous }}&type={{ type }}">&larr; Previous</a></li>
            <li class="next"><a href="display?wd={{ query }}&start={{ next }}&type={{ type }}">Next &rarr;</a></li>
        </ul>
        </div>
    </div>
</header>
{#{% endblock content %}#}
</body>
</html>

djangoProject/hellosite/templates/begin/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>检索系统</title>
</head>
<body>
{% extends "begin/base.html" %}

{% block content %}
{% endblock content %}
</body>
</html>

djangoProject/hellosite/templates/begin/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title style="font-family: 'PingFang SC'">Papers Network</title>
    <style>
        .check_box{
            left:50%;
        }
        .label_check{
            font-family: "Helvetica Neue";
            font-size: 15px;
        }
    </style>
</head>
<body>
{% extends "begin/base.html" %}

{% block content %}
    <header class="text-center text-white masthead">
        <div class="container ">
            <div class="spacer"></div>
            <div class="row">
                <div>
                    <h1 class="p1">Just search what you want!</h1>
                </div>

                <div class="spacer_s"></div>
                <div class="form-horizontal input-append">
                    <div class="col-lg-6">
                        <div class="input-group input-group-lg">
                            <input type="text" style="width: 520px" class="form-control p1" size="80" id="search_content"
                                   placeholder="For Example: Knowledge Graph">
                            <span class="input-group-btn">
                        <button class="btn btn-success p1" type="submit" onclick="search()">Go!</button>
                            </span>
                        </div>
                        <br>
                        <div class="form-check col-lg-12 check_box">
                        <input class="form-check-input"    type="radio" name="flexRadioDefault" id="default">
                        <label class="form-check-label label_check"  for="default">Default</label>
                            &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        <input class="form-check-input "  type="radio" name="flexRadioDefault" id="advanced">
                        <label class="form-check-label label_check"  for="advanced">Advanced</label>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </header>
    <script>
        function search() {
            let search_content = document.getElementById("search_content").value;
            {#console.log(localStorage.getItem("result"));#}
            {#let default_box_value=document.getElementById("default").value;#}
            {#let advanced_box_value=document.getElementById("advanced").value;#}
            let type;
            if(document.getElementById("default").checked)
                type=0;
            else
                type=1;
            document.location.href = "display?wd=" + search_content+"&start=0"+"&type="+type;
        }
    </script>
{% endblock content %}
</body>
</html>

djangoProject/hellosite/templates/begin/test.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>知识图谱</title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <link rel="shortcut icon" href="">
    <script src="http://cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>
<style type="text/css">
body {
	background-color: #272b30;
	padding: 30px 40px;
	text-align: center;
    font-family: OpenSans-Light, PingFang SC, Hiragino Sans GB, Microsoft Yahei, Microsoft Jhenghei, sans-serif;
}

#indicator {
	position: absolute;
	left: 60px;
	bottom: 120px;
    text-align: left;
    color: #f2f2f2;
    font-size: 12px;
}

#indicator>div {
    margin-bottom: 4px;
}

#indicator span {
    display: inline-block;
    width: 30px;
    height: 14px;
    position: relative;
    top: 2px;
    margin-right: 8px;
}

.links line {
	stroke: rgb(240, 240, 240);
	stroke-opactity: 0.2;
}

.nodes circle {
	stroke: #fff;
	stroke-width: 1.5px;
}

.texts text {
    display: none;
}

</style>
<body>

	<!-- 绘制标题样式 -->
	<h1 style="color:#fff;font-size:32px;margin-bottom:0px;text-align:center;margin-left:40px;">Star Wars</h1>

	<!-- 第一个布局 绘制知识图谱主图 -->
	<div style="text-align: center; position:relative;">
		<svg width="800" height="560" style="margin-right:80px;margin-bottom:-40px;" id="svg1">
    	</svg>

    	<!-- 绘制图例 -->
		<div id="indicator">
	    </div>

	    <!-- 绘制模式选择 -->
	    <div id="mode">
	    </div>

	    <!-- 绘制搜索框 -->
	    <div id="search">
	    </div>

	    <!-- 绘制右边显示结果 -->
	    <div id="info">
	    </div>
	</div>

	<!-- 第二个布局 下部分时间点 文本居中 相对定位-->
	<div style="text-align: center; position:relative;">
		<svg width="960" height="240" style="margin-right:60px;margin-bottom:-40px;" id="svg1">
			<g></g>
    	</svg>
	</div>

</body>
{% extends "begin/base.html" %}
<!-- 增加D3元素库 -->
<script src="https://d3js.org/d3.v4.min.js"></script>
<!-- 补充JS代码 -->
<script type="text/javascript">
	$(document).ready(function() {

		//定义svg变量将布局svg1选出来
		var svg = d3.select("#svg1"),
			width = svg.attr("width"),
			height = svg.attr("height");
		//定义name变量制作图标
		var names = ['Films', 'Characters', 'Planets', 'Starships', 'Vehicles', 'Species'];
		var colors = ['#6ca46c', '#4e88af', '#ca635f', '#d2907c', '#d6744d', '#ded295'];

		//背景颜色设置 补充CSS样式设置字体布局
		for (var i=0; i < names.length; i++) {
			$('#indicator').append("<div><span style='background-color:" + colors[i] + "'></span>" + names[i] + "</div>");
		}

		//利用d3.forceSimulation()定义关系图 包括设置边link、排斥电荷charge、关系图中心点
		var simulation = d3.forceSimulation()
	        .force("link", d3.forceLink().id(function(d) {
	            return d.id;
	        }))
	        .force("charge", d3.forceManyBody())
	        .force("center", d3.forceCenter(width / 2, height / 2));


	    //存储关系图的数据
	    var graph;

	    //定义d3.json请求python处理好的节点及边 请求成功返回数据，否则报错
	    d3.json("starwar_alldata.json", function(error, data) {
	    	if(error) throw error;
	    	graph = data;
	    	console.log(graph);

	    	//D3映射数据至HTML中
	    	//g用于绘制所有边,selectALL选中所有的line,并绑定数据data(graph.links),enter().append("line")添加元素
	    	//数据驱动文档,设置边的粗细
	    	var link = svg.append("g").attr("class","links").selectAll("line").data(graph.links).enter()
	    	.append("line").attr("stroke-width", function(d) {
	    		//return Math.sqrt(d.value);
	    		return 1; //所有线宽度均为1
	    	});

	    	//添加所有的点
	    	//selectAll("circle")选中所有的圆并绑定数据,圆的直径为d.size
	    	//再定义圆的填充色,同样数据驱动样式,圆没有描边,圆的名字为d.id
	    	//call()函数：拖动函数,当拖动开始绑定dragstarted函数，拖动进行和拖动结束也绑定函数
	    	var node = svg.append("g").attr("class", "nodes").selectAll("circle").data(graph.nodes).enter()
	    	.append("circle").attr("r", function(d) {
	    		return d.size;
	    	}).attr("fill", function(d) {
	    		return colors[d.group];
	    	}).attr("stroke", "none").attr("name", function(d) {
	    		return d.id;
	    	}).call(d3.drag()
	    		.on("start", dragstarted)
	    		.on("drag", dragged)
	    		.on("end", dragended)
	    	);

	    	//两种表示放肆
	    	//显示所有的文本
	    	//设置大小、填充颜色、名字、text()设置文本
	    	//attr("text-anchor", "middle")文本居中

	    	var text = svg.append("g").attr("class", "texts").selectAll("text").data(graph.nodes).enter()
	    	.append("text").attr("font-size", function(d) {
                return d.size;
            }).attr("fill", function(d) {
                return colors[d.group];
            }).attr('name', function(d) {
                return d.id;
            }).text(function(d) {
                return d.id;
            }).attr('text-anchor', 'middle').call(d3.drag()
                .on("start", dragstarted)
                .on("drag", dragged)
                .on("end", dragended)
            );

            /*
	    	var text = svg.append("g").attr("class", "texts").selectAll("text").data(graph.noedes).enter().append("text").attr("font-size", function(d) {
	    		return d.size;
	    	}).attr("fill", function(d) {
	    		return colors[d.graph];
	    	}).attr("name", function(d) {
	    		return d.id;
	    	}).text(function(d) {
	    		return d.id;
	    	}).attr("text-anchor", "middle").call(d3.drag()
	    		.on("start", dragstarted)
	    		.on("drag", dragged)
	    		.on("end", dragended)
	    	);
	    	*/


	    	//圆增加title
	    	node.append("title").text(function(d) {
	    		return d.id;
	    	})

	    	//simulation
	    	//ticked 数据初始化，并生成图形

	    	simulation
	            .nodes(graph.nodes)
	            .on("tick", ticked);

	        simulation.force("link")
	            .links(graph.links);

	        //ticked()函数确定link线的起始点x、y坐标 node确定中心点 文本通过translate平移变化
	        function ticked() {
	            link
	                .attr("x1", function(d) {
	                    return d.source.x;
	                })
	                .attr("y1", function(d) {
	                    return d.source.y;
	                })
	                .attr("x2", function(d) {
	                    return d.target.x;
	                })
	                .attr("y2", function(d) {
	                    return d.target.y;
	                });

	            node
	                .attr("cx", function(d) {
	                    return d.x;
	                })
	                .attr("cy", function(d) {
	                    return d.y;
	                });

	            text.
	            attr('transform', function(d) {
	                return 'translate(' + d.x + ',' + (d.y + d.size / 2) + ')';
	            });
	        }
	    });


	    // Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension
	    // 本地json数据需要放置服务器中请求 XAMPP


	    //拖动函数代码
	    //var dragging = false;

	    //开始拖动并更新相应的点
	    function dragstarted(d) {
	        if (!d3.event.active) simulation.alphaTarget(0.3).restart();
	        d.fx = d.x;
	        d.fy = d.y;
	        //dragging = true;
	    }

	    //拖动进行中
	    function dragged(d) {
	        d.fx = d3.event.x;
	        d.fy = d3.event.y;
	    }

	    //拖动结束
	    function dragended(d) {
	        if (!d3.event.active) simulation.alphaTarget(0);
	        d.fx = null;
	        d.fy = null;
	        //dragging = false;
	    }



	});
</script>
</html>

djangoProject/hellosite/templates/begin/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户</title>
</head>
<body>
{% extends "begin/base.html" %}

{% block content %}
<p>所有用户</p>
    <ul>
    {% for user in users %}
        <li>{{ user }}</li>
    {% empty %}
        <li>暂无用户！</li>
    {% endfor %}
    </ul>
{% endblock content %}
</body>
</html>

djangoProject/hellosite/templates/begin/vdemo.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title></title>
</head>
<body>
<div id="app">
改编不是乱编，{% verbatim %}{{ string_from_api }}{% endverbatim %}
</div>
<script src="https://cdn.jsdelivr.net/npm/vue@latest/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios@0.18.0/dist/axios.min.js"></script>
<script>
var app = new Vue({
    el: '#app',
    data () {
        return {
            string_from_api: '要向全国人民谢罪的！'
        }
    },
{#mounted () {#}
{#    axios#}
{#    .get('api/666')#}
{#    .then(response => (this.string_from_api = response.data))#}
{#    }           #}
})
</script>
</body>
</html>

djangoProject/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>成了哈哈哈哈哈！</title>
</head>
<body>
{% extends "../hellosite/templates/begin/base.html" %}
{% block content %}
  <p>啊啊哈哈哈哈</p>
{% endblock content %}
</body>
</html>